http:
  # Middlewares
  middlewares:
    auth-middleware:
      forwardAuth:
        address: "http://auth:5000/auth"
        authRequestHeaders:
          - "x-pretest"
        authResponseHeaders:
          - "X-Auth-User"
        trustForwardHeader: true
    add-auth-headers:
      headers:
        customRequestHeaders:
          X-Original-URI: "{path}"
  # Routers
  routers:
    health-router:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      middlewares:
        - add-auth-headers
        - auth-middleware
      service: health-service

  # Services
  services:
    health-service:
      loadBalancer:
        servers:
          - url: "http://auth:5000/health"