http:
  # Middlewares
  middlewares:
    auth-middleware:
      forwardAuth:
        address: "http://auth:5000/auth"
        authRequestHeaders:
          - "x-pretest"
        authResponseHeaders:
          - "X-Auth-User"
        trustForwardHeader: true
    
    rewrite-to-health:
      replacePath:
        path: "/health"
    
    add-auth-headers:
      headers:
        customRequestHeaders:
          X-Original-URI: "{path}"
  
  # Routers
  routers:
    health-router:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      middlewares:
        - add-auth-headers
        - auth-middleware
        - rewrite-to-health
      service: auth-service

  # Services
  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth:5000"